### ISSUE TITLE
Senaste aktiekurs laddas inte in

### ISSUE THREAD

**Issue by jepl4052** [nnava/nnava.github.io#10]
Problem med att ladda in aktiekurser automatiskt, priser visas som 0,00 kr.

<img width="954" alt="skarmavbild 2017-11-13 kl 16 47 40" src="https://user-images.githubusercontent.com/24591486/32734507-875480dc-c892-11e7-8960-03f4e97e1fc0.png">

**Comment by nnava** [comment]
Stämmer. Har försökt hitta alternativ till Yahoo Finance men det ser mörkt
ut.

Deras svar om detta
https://forums.yahoo.net/t5/Known-issues-and-updates/Yahoo-Finance-API-disabled/m-p/392760#M14

Den 13 nov. 2017 16:49 skrev "Jens Plate" <notifications@github.com>:

**Comment by nnava** [comment]
En klen tröst men nu sparas senaste pris i localstorage och läses in igen när man laddar portföljöversikten.

Kommer att fortsätta leta alternativ för att hämta senaste pris.

**Comment by SimonZonabend** [comment]
Fina diagram och staplar!!
Kan man använda googles api: Fråga på en åt gången.. detta fungerar fint:

https://finance.google.com/finance?q=NOBINA.ST&output=json

mvh Simon

**Comment by nnava** [comment]
Hade funkat om Yahoo hade haft kvar sin YQL, men dess funktionalitet att hämta data från htmlstring stängdes ner i samma veva som de stängde tjänsten för att hämta värdepappersinformation. Har inte hittat någon motsvarighet.

**Comment by nnava** [comment]
Har lagt en fix för detta, nyttjar cors.io och hämtar från Google finance. Tack @SimonZonabend för tipset om Google!

Nackdelen är att jag styr inte alls över cors.io, när den är nere så kommer det inte gå att hämta. Får ev komplettera med fler gratis proxys framöver.
