### ISSUE TITLE
"TYSK SOL SKATT UTD" dras inte av på utdelning

### ISSUE THREAD

**Issue by Ragowit** [nnava/nnava.github.io#12]
Fick nyss utdelning från "SIE.DE" (DE0007236101), och hemsidan visar "UTDELNING" minus "UTL KUPSKATT" som mitt utdelningsvärde. Men det finns även en "TYSK SOL SKATT UTD" på 0,50 kr som jag antar även ska dras bort?

[TYSK SOL SKATT UTD.zip](https://github.com/nnava/nnava.github.io/files/1702655/TYSK.SOL.SKATT.UTD.zip)

**Comment by nnava** [comment]
Tack för felrapporten och exempelfilen! Har kompletterat med TYSK SOL SKATT UTD nu. Testa gärna.

**Comment by Ragowit** [comment]
Har testat, och det verkar fungera fint nu! Stänger denna issue.
