### ISSUE TITLE
Just Energy Group Inc (Kanada) visas som USD/Amerika

### ISSUE THREAD

**Issue by Ragowit** [nnava/nnava.github.io#13]
Just Energy Group Inc (CA48213W1014) visas med valutan USD i Portföljöversikt, samt med amerikansk flagga under förväntade utdelningar.

[Just Energy Group Inc.zip](https://github.com/nnava/nnava.github.io/files/1702735/Just.Energy.Group.Inc.zip)

**Comment by nnava** [comment]
Kollat på denna, men den är lurig. 

Finns som USD
https://www.avanza.se/aktier/om-aktien.html/410896/just-energy-group-inc

Där den också har samma ISIN och symbol (kortnamn) som den kanadensiska.

Har just nu ingen idé hur det ska lösas tyvärr. Ser du några möjligheter att lista ut om det är USD eller CAD? En grej vore väl valutakursen men det känns rackligt.

**Comment by Ragowit** [comment]
Ouch, trodde inte att de skulle ha exakt samma ISIN. Och .csv-filen berättar inte vilken marknad (TSE, Toronto Stock Exchange) jag köpte från. Är rädd att det inte finns så mycket att göra här som gör det hela 100% korrekt. :/ Någon funktion som känner igen vissa sådana här aktier och låter användaren få ställa in vad det är? Men låter som mycket jobb för väldigt få specifika fall.

**Comment by nnava** [comment]
Blir lite mycket jobb kring denna så stänger den om du inte känner för att skapa en lösning från ditt håll? Är såklart välkommet

**Comment by Ragowit** [comment]
Nah, det blir korrekta siffror när väl utdelningen har varit och det räcker för mig just nu.
