### ISSUE TITLE
"Ladda grafer" tänds aldrig upp under "Portföljöversikt"

### ISSUE THREAD

**Issue by Ragowit** [nnava/nnava.github.io#17]
Fältet "Bransch" har en massa tomma värden, men det hjälpte inte att fylla i dessa. Telia hade "Telekomoperatörer" som var rödmarkerad, att ändra detta gjorde heller ingenting.

Det är mest de två utdelningssektionerna längst ner på sidan som jag är intresserad utav att se.

**Comment by Ragowit** [comment]
Har nu testat lite mer, och detta fungerar inte för mig i:
Google Chrome 67.0.3396.99 (64-bit)
Mozilla Firefox 61.0 (64-bit)
Microsoft Edge 42.17134.1.0

**Comment by simonosterberg** [comment]
Har du några utrikiska aktier i portföljen? Har upptäckt att Ladda grafer aldrig tänds om jag läser in en .csv som innehåller i mitt fall amerikanska och kanadensiska aktier. konsolen i chromes utvecklingsverktyg ger felmeddelanden som jag tolkar att den inte klarar av att konvertera USD och CAD till SEK. Bifogar konsoloutputen ifall det kanske hjälper
[nnava.github.io-1530220975824.txt](https://github.com/nnava/nnava.github.io/files/2147018/nnava.github.io-1530220975824.txt)

**Comment by Ragowit** [comment]
Ja, det stämmer att jag har några utrikiska aktier i min portfölj. Däribland just amerikanska och kanadensiska som du nämner.

**Comment by SimonZonabend** [comment]
Ser ut som anropen till https://api.fixer.io/latest?base= har blivit ersatta av nya där det krävs api key: https://github.com/fixerAPI/fixer#readme
Behövs alltså skruvas i filen currencydataservice.js...

**Comment by nnava** [comment]
Yes, har kollat på det men är dessvärre på semester. Hoppas kunna lösa
under nästa vecka.

Den tis 3 juli 2018 22:59Simon Zonabend <notifications@github.com> skrev:

**Comment by dataheaven** [comment]
Ragowit har du Atlas Copco i portföljen? Jag har en teori om att avknoppningen av Epiroc ställer till det.

Om jag laddar in en portfölj som innehåller Atlas Copco, så syns just Atlas Copco inte i spreadsheeten under Portföljöversikt. Kanske behöver bara utdelningsdatan uppdateras?

nnava hur brukar du göra för att uppdatera utdelningsdatan, kör du något skript som uppdaterar den automatiskt eller är det mer manuellt jobb?

**Comment by nnava** [comment]
Har justerat hämtningen av valutakurser så nu ska det gå bra att ladda graferna i portföljöversikten.

**Comment by nnava** [comment]
@dataheaven nu ska även Atlas vara med i spreadsheeten. Jag har tidigare haft ett enkelt sätt att få ut alla aktier för t.ex. Stockholmsbörsen men den möjligheten har plockats bort. Har gjort att jag måste göra en del manuella inslag när t.ex. ISIN justeras. 

Utdelningsdatat ska nu vara up to date
