### ISSUE TITLE
Vissa aktier läses inte in

### ISSUE THREAD

**Issue by Ragowit** [nnava/nnava.github.io#21]
Jag har några aktier i min portfölj. Dessa kommer inte med.
[transaktionsfil.zip](https://github.com/nnava/nnava.github.io/files/3000286/transaktionsfil.zip)

- BET-AT-HOME.COM AG O.N. (ACX)
- Betsson AB ser. B (BETS B)
- Björn Borg AB (BORG)
- CENIT AG O.N. (CSH)
- ENVITEC BIOGAS O.N. (ETG)
- Navios Maritime Acquisition Corporation (NNA)
- NetEnt AB ser. B (NET B)
- OFS Capital Corporation (OFS)
- TRANSALTA RENEWABLES INC (RNW)

**Comment by Ragowit** [comment]
Med transaktionsfilen i första posten så syns fortfarande inte:

- BET-AT-HOME.COM AG O.N. (ACX)
- CENIT AG O.N. (CSH)
- ENVITEC BIOGAS O.N. (ETG)

**Comment by nnava** [comment]
Har ingenstans att hämta data från. Vore toppen kunna hämta från Avanza men
de finns inte där. Eller letar jag dåligt?

Den sön 14 juli 2019 12:49Markus Persson <notifications@github.com> skrev:

**Comment by Ragowit** [comment]
Alla tre är från den tyska marknaden. Använder Nordnet själv och nu när jag testar att söka på Avanza så hittar jag själv inget. Avanza kanske inte har den tyska marknaden?
