### ISSUE TITLE
Felaktigt antal Nordea Bank Abp aktier

### ISSUE THREAD

**Issue by simonosterberg** [nnava/nnava.github.io#24]
Antalet Nordea Bank Abp aktier i portföljöversikten är dubblat mot det faktiska antalet. 
[nordea.csv.zip](https://github.com/nnava/nnava.github.io/files/3168959/nordea.csv.zip)
Bifogas Avanza cvs med relevanta rader. Det faktiska antalet är 24st men visas som 48st.

**Comment by nnava** [comment]
Tackar, är nu löst.
