### ISSUE TITLE
Portföljöversikt laddar inte in senaste pris/växlingskurs

### ISSUE THREAD

**Issue by Ragowit** [nnava/nnava.github.io#25]
Portföljöversikt laddar inte längre in senaste pris på aktier, eller ibland bara ett fåtal. Denna sida verkar vara beroende utav denna information då graferna efter "Ladda grafer" blir väldigt tomma.

Alla förväntade utländska utdelningar blir också i 0 kr. Gissar att det är någon hämtning utav senaste växlingskurs som strular?

**Comment by simonosterberg** [comment]
Verkar som det beror på att cors.io som används som proxy för att hämta kurser är nere,
mer info https://github.com/pierce403/cors.io/issues/5

**Comment by nnava** [comment]
Tack för att ni noterade, har bytt proxy nu så det ska funka.

**Comment by simonosterberg** [comment]
Nya proxyn verkar inte riktigt gilla hur snabbt requests skickas. Får väldigt mycket "429 (Too Many Requests)" på de requests som använder proxyn på portföljöversikten.

**Comment by simonosterberg** [comment]
Såg nu i response på requesten detta så det är själva proxyn som har ganska hårda begränsningar:

"The origin "https://nnava.github.io" has sent too many requests.
The number of requests is limited to 200 per 60 minutes. Please self-host CORS Anywhere if you need more quota. See https://github.com/Rob--W/cors-anywhere#demo-server"

**Comment by nnava** [comment]
Kör på "egen" cors.io nu. Hoppas det ska lira
