### ISSUE TITLE
Enstaka aktier uppdateras ej

### ISSUE THREAD

**Issue by epatric** [nnava/nnava.github.io#26]
Jag har fn. problem med 3 svenska värdepapper där data inte uppdateras korrekt:

Ingen data uppdateras:
CLX Communications - SE0007439112 (för övrigt bytt namn till Sinch)
Instalco Intressenter - SE0009664253

Utdelning uppdateras ej:
XACT Högutdelande - SE0009778954

**Comment by nnava** [comment]
Tack för felrapporten, ska gå att se Sinch och Instalco, har inget utdelningsdata för XACT så den är svårare att lösa.

**Comment by epatric** [comment]
Stort tack!

Är själv ingen kodare och vet inte hur du plockar hem utdelningsdata men det går att se utdelningsdata här (under historiska kurser/endast utdelningar):
https://handelsbanken-marknadsinformation.se/app/instrument/XACTHDIVi/17921/Historik

![image](https://user-images.githubusercontent.com/52911257/75605795-539d0a00-5ae6-11ea-8fd3-7dc3d277dcc0.png)
