### ISSUE TITLE
Portföljöversikt läser bara data från en fil

### ISSUE THREAD

**Issue by Ragowit** [nnava/nnava.github.io#3]
Jag laddar in två filer från Nordnet ("transaktionsfil.csv" och "transaktionsfil (1).csv") från två olika depåer som jag har. Och när jag klickar på Portföljöversikt och sedan på de två knapparna där så verkar enbart data från den ena filen läsas in.

**Comment by nnava** [comment]
Har gjort en hel del korrigeringar för portföljdatat som kommer från Nordnet. Har du möjlighet att testa om detta?

**Comment by Ragowit** [comment]
Verkar fungera nu, tack så mycket!
