### ISSUE TITLE
Saknar aktien Akelius D

### ISSUE THREAD

**Issue by epatric** [nnava/nnava.github.io#30]
Aktie: AKEL D
ISIN: SE0013110186
Noterades 2019-10-04

**Comment by nnava** [comment]
Tack, har lagt in det nu

**Comment by epatric** [comment]
Tack! Dock behövs kursen uppdateras då aktien (och utdelningen) handlas i EUR.

**Comment by nnava** [comment]
Sorry lite seg. Justerat till EUR nu

**Comment by epatric** [comment]
Tack!
