### ISSUE TITLE
"Utdelningar/utgifter - nuvarande år" som senaste 12 månaderna + 3 kommande

### ISSUE THREAD

**Issue by Ragowit** [nnava/nnava.github.io#4]
"Max om utdelning" har en intressant uppställning där denna person listar sina senaste 12 utdelningsmånaderna + 3 kommande. Här kan det ses: http://maxutdelning.blogspot.se/2017/02/manadsrapport-januari-2017.html

Detta tycker jag ger en bättre bild och skulle uppskatta om det blev en verklighet på denna sida. För just nu att bara kunna se januari och februari och sedan de kommande 10 månaderna säger inte så mycket enligt mitt tycke.

**Comment by nnava** [comment]
Tack för förslaget! 

Jag har tänkt liknande faktiskt och jobbar just nu på att plocka fram ens förväntade utdelningar, när det är på plats så skulle det kunna illustreras i det diagrammet.

**Comment by nnava** [comment]
En bit på vägen är det nya diagrammet/tabellen Erhållna/förväntade utdelningar. Dock tas inte utgifter med. Några reflektioner på Erhållna/förväntade utdelningar?

**Comment by Ragowit** [comment]
Ser bra ut so far, har inga övriga reflektioner.

**Comment by nnava** [comment]
Möjligt att välja rullande 12 månader finns nu inlagt, påverkar tre utdelningsgrafer.

**Comment by nnava** [comment]
Och nu även för Utdelningar/utgifter

**Comment by Ragowit** [comment]
Jag är mycket nöjd över hur det fungerar just nu, och stänger denna issue. Tack för att du implementerat detta!
