### ISSUE TITLE
Skriptet kraschar om det inte finns några utdelningar alls

### ISSUE THREAD

**Issue by danielinvesterar** [nnava/nnava.github.io#5]
Om man inte har några utdelningar alls så kommer setChartData() i chartdividendexpenses.js få "undefined" som Year och        

 var datesInPeriod = dateperiod.getDateRange(startPeriod, endPeriod);

kommer kasta ett undantag för att det är trasiga Date-objekt som inte går att parsa.

**Comment by nnava** [comment]
Tack för buggrapporten!

Lagt till undantag för detta. In och testa

**Comment by danielinvesterar** [comment]
Ser ut att fungera. Fick något annat fel när jag tog bort csv-filer och la till en debug.csv-fil, men det är ett annat problem som man kan undvika genom att ladda om sidan.
