### ISSUE TITLE
En diskrepans på -0,00059 kronor i pris tolkas som -1 krona courtage

### ISSUE THREAD

**Issue by danielinvesterar** [nnava/nnava.github.io#6]
Kurs: 113,15
Antal: 441,8913
Belopp: -50000

i getCourtageSumBuy() i alasqlavanza.js kommer courtaget beräknas till -0,000595 vilket blir -0.00 efter "(% 1).toFixed(2)". Sedan gör koden Math.floor och får -1.

Negativa värden här ställer till det rejält i procentberäkningar.

**Comment by danielinvesterar** [comment]
Fortfarande ett problem efter den senaste patchen.

**Comment by nnava** [comment]
Lagt in ett undantag för hantera <= 0 värde

Men vet inte om jag är med på exemplet ovan, är det från köp av fond?

**Comment by danielinvesterar** [comment]
Ja, det är fondandelar. Där sätter man ett belopp i köpordern men det är sällan det blir exakt. Det kan diffa upp mot ett öre eller mer.

Men jag tror något gått riktigt fel i courtageberäkningen nu. Det ser inte bra ut alls. Det har dykt upp små säljcourtage på 3 kronor några år då jag bara sålt fonder (inga courtage) och köpcourtage för många aktieaffärer verkar saknas. Det brukade vara helt rätt bortsett från det där avrundningsfelet.

**Comment by nnava** [comment]
Ok, lagt tillbaka tidigare version.

Jag ska ändra så att fonder inte tas med i beräkningen av courtage, det är verkar vara huvudproblemet här.

**Comment by nnava** [comment]
Fonder gav minusposter, nu ska de vara exkluderat från beräkningen, tack för att du uppmärksammade.

Däremot har jag noterat att det i vissa fall blir en felaktig summering på en försäljning, vilket jag ska kolla vidare på. 

En 100% lösning som även fungerar för utländska värdepapper är om Avanza kompletterar sin export med en avgiftskolumn, jag har påpekat det tidigare men ska påminna om detta.

**Comment by danielinvesterar** [comment]
Ser ut att fungera. Tack!
