### ISSUE TITLE
Sandvik inlösenrätter tolkade som försäljning

### ISSUE THREAD

**Issue by danielinvesterar** [nnava/nnava.github.io#7]
2005 delade Sandvik ut sin utdelning i form av inlösenrätter. nnava tolkar de som att man sålt aktier vilket gör att köp/sälj hamnar på minus (om det inte finns några andra köp det året).

http://www.mynewsdesk.com/se/pressreleases/avista-notering-av-inloesenraetter-och-inloesenaktier-i-sandvik-ab-114-05-44406

Relevanta rader i csv-filen:
2005-07-07	1234567	Sälj	SAND SR1	-100	4,22	273	SEK	SE0001419003
2005-05-10	1234567	Insättning från d.2841401	SAND SR1	100	3,94	-	SEK	SE0001419003

Jag tyckte mig se en lista på värdepapper som skulle filtreras. Kanske är det här ett till. Kanske går det att se på namnet (suffix SR1, DR, TR, ...) att det inte är en "riktig" försäljning (såvida man nu inte spekulerat i dem).

**Comment by nnava** [comment]
Lagt till så även Sandvik hantera för undatag IL och SR1

Testa gärna. Tror även denna kommer lösa -1 för courtaget (https://github.com/nnava/nnava.github.io/issues/6)

**Comment by danielinvesterar** [comment]
Funkar! Men löste inte #6.
