### ISSUE TITLE
Procentkurvan för "Köp/sälj/nettoinvesterat total - år" blir meningslös om ett år är <= 0

### ISSUE THREAD

**Issue by danielinvesterar** [nnava/nnava.github.io#8]
"Köp/sälj/nettoinvesterat total - år" har en kurva för procent ("Nettoutveckling"). Om någon av datapunkterna är mindre än noll så blir procentsatsen för det året och året efter negativ. 

Jag tror det är bäst att undvika alla procentsatser som man fått genom att dividera två tal med olika tecken. Sedan bör man nog sätta en övre begränsning på grafen så att inte division med väldigt små positiva tal gör grafen oläsbar för att skalan blir 0 till 1000000%.

**Comment by nnava** [comment]
Överväger att plocka bort linjen. Ska bara sova på saken.

**Comment by nnava** [comment]
Varit i kontakt med Telerik. Ett alternativ hade varit att använda log-skala vid stora differenser men detta fungerar nedast om det är positiva värden. 

Plockat bort linjen nu.

**Comment by nnava** [comment]
Försökte hitta ngn mejl att nå dig på. Kan du skicka ett mejl till mig lill4ekonomen@gmail.com
