### ISSUE TITLE
Skriptkrasch i saveValues om man lägger till fler filer

### ISSUE THREAD

**Issue by danielinvesterar** [nnava/nnava.github.io#9]
När man lägger till fler filer så försöker skriptet spara vilka konton man har valt. Om konton har numeriska "namn" så kraschar det på rad 75 i multiselectorportfolio.js

```
multiselectorportfolio.js?bust=215:75 Uncaught TypeError: entry.value.endsWith is not a function
    at https://nnava.github.io/js/multiselectorportfolio.js?bust=215:75:32
```

`if(entry.value.endsWith("csv")) {`

misslyckas för att value är ett nummer, inte en sträng.

**Comment by nnava** [comment]
Tackar för felrapporten! Checkat in en rättning. 

Anar en testare i dig Daniel 👍

**Comment by nnava** [comment]
Testat denna?

**Comment by danielinvesterar** [comment]
Verkar fungera att lägga till flera filer, en i taget.
